import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { CartProvider } from "@/library/cart.context";
import '@/app/globals.css';
import NextAuthWrapper from "@/library/next.auth.wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "@webdemo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <AntdRegistry>
          <CartProvider>
            <NextAuthWrapper>
              {children}
            </NextAuthWrapper>
          </CartProvider>
        </AntdRegistry>

      </body>
    </html>
  );
}
